Rem Simple Arkanoid game example
Rem Generated by AI on 2026-08-31
Rem Successfully runs in QBasic 1.0 and compiles in QB64 2.1

Dim A(350)
Dim blocks(3, 8)

Screen 9
Cls

Rem draw a paddle
Line (0, 0)-(60, 10), 10, BF
Line (0, 0)-(60, 10), 15, B
Get (0, 0)-(60, 10), A()
Cls

px = 290: py = 320 ' Paddle coordinates
bx = 320: by = 200 ' Ball coordinates
dx = 4: dy = -4 ' Ball speed
bsize = 6 ' Half-size of the square ball

Rem --- Initial level rendering ---
Color 14
Print "=== QBASIC ARKANOID ==="
Line (0, 30)-(639, 340), 15, B ' Screen boundaries

Rem Fill and draw bricks (3 rows of 8 bricks)
For row = 0 To 2
    For col = 0 To 7
        blocks(row, col) = 1 ' 1 - brick is intact
        bx1 = col * 75 + 25
        by1 = row * 25 + 60
        Line (bx1, by1)-(bx1 + 65, by1 + 15), 9 + row, BF
        Line (bx1, by1)-(bx1 + 65, by1 + 15), 15, B
    Next col
Next row

Rem Draw initial paddle
Put (px, py), A(), PSet

Rem --- Main game loop ---
Do
    Rem --- Frame rate limiting (Timer delay) ---
    t! = Timer: Do: Loop While Timer = t!

    Rem --- Input handling (paddle control) ---
    kbd$ = InKey$
    If kbd$ = Chr$(0) + Chr$(75) Then ' Left arrow key
        If px > 5 Then
            Put (px, py), A(), Xor
            px = px - 15
            Put (px, py), A(), Xor
        End If
    End If
    If kbd$ = Chr$(0) + Chr$(77) Then ' Right arrow key
        If px < 575 Then
            Put (px, py), A(), Xor
            px = px + 15
            Put (px, py), A(), Xor
        End If
    End If
    If kbd$ = Chr$(27) Then Exit Do ' ESC key

    Rem --- Erase ball ---
    Line (bx - bsize, by - bsize)-(bx + bsize, by + bsize), 0, BF

    Rem Update coordinates
    bx = bx + dx
    by = by + dy

    Rem --- Wall collision check ---
    If bx <= 5 + bsize Or bx >= 635 - bsize Then dx = -dx
    If by <= 35 + bsize Then dy = -dy

    Rem --- Brick collision check ---
    If by > 55 And by < 145 Then
        col = (bx - 25) \ 75
        row = (by - 60) \ 25

        If col >= 0 And col <= 7 And row >= 0 And row <= 2 Then
            If blocks(row, col) = 1 Then
                bx1 = col * 75 + 25
                by1 = row * 25 + 60
                If bx >= bx1 And bx <= bx1 + 65 Then
                    blocks(row, col) = 0 ' Destroy the brick
                    Line (bx1, by1)-(bx1 + 65, by1 + 15), 0, BF ' Erase the brick
                    dy = -dy ' Bounce
                    Sound 800, 0.05
                End If
            End If
        End If
    End If

    Rem --- Paddle collision check ---
    If by >= py - bsize And by <= py + 10 Then
        If bx >= px And bx <= px + 60 Then
            dy = -dy
            by = py - bsize - 1
            Put (px, py), A(), PSet ' Restore paddle graphics
            Sound 400, 0.05
        End If
    End If

    Rem --- Game over check ---
    If by > 340 Then
        Cls
        Locate 12, 35: Print "GAME OVER"
        Sound 150, 5
        Sleep 3
        Exit Do
    End If

    Rem --- Draw ball ---
    Line (bx - bsize, by - bsize)-(bx + bsize, by + bsize), 12, BF

Loop
